# users/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import RegisterUserView, UserViewSet, UserProfileView

router = DefaultRouter()
# The router automatically generates CRUD URLs for UserViewSet
router.register(r'', UserViewSet, basename='users')

urlpatterns = [
    # This URL is for user registration
    path('register/', RegisterUserView.as_view(), name='user-register'),

    # This URL is for the authenticated user's own profile
    path('profile/', UserProfileView.as_view(), name='user-profile'),

    # This includes the URLs generated by the router
    path('', include(router.urls)),
]